logging:
  level:
    io.github.flowrapp: WARN

spring:
  docker:
    compose:
      enabled: false
  datasource:
    main-postgres:
      jdbcUrl: jdbc:postgresql://${MAIN_POSTGRES_URL}/flowra
      username: ${MAIN_POSTGRES_USERNAME}
      password: ${MAIN_POSTGRES_PASSWORD}