logging:
  level:
    io.github.flowrapp: DEBUG
    org.springframework.web: DEBUG

spring:
  datasource:
    main-postgres:
      jdbcUrl: jdbc:postgresql://localhost:32010/flowrapp
      username: ${MAIN_POSTGRES_USERNAME:postgres}
      password: ${MAIN_POSTGRES_PASSWORD:postgres}
  jpa:
    show-sql: true