spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    main-postgres:
      jdbcUrl: jdbc:postgresql://localhost:32010/flowrapp
      username: ${MAIN_POSTGRES_USERNAME}
      password: ${MAIN_POSTGRES_PASSWORD}