spring:
  application:
    name: flowrapp

  mvc:
    problemdetails:
      enabled: true

  threads:
    virtual:
      enabled: false # Enable for virtual threads

  # Datasource Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SCHEMA:flowrapp_management}
  datasource:
    neon-azure:
      driverClassName: org.postgresql.Driver
  docker:
    compose:
      file: code/boot/src/test/resources/compose/docker-compose.yml
      enabled: false

app:
  # OAuth2 Client Configuration
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}

# Mail Configuration
simplejavamail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
  transportstrategy: SMTP_TLS

# Swagger OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  packages-to-scan: io.github.flowrapp.infrastructure.input.rest

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]

server:
  servlet:
    context-path: /flowrapp
  port: 8080
