spring:
  mvc:
    problemdetails:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: flowrapp_management
  datasource:
    main-postgres:
      driverClassName: org.postgresql.Driver
  docker:
    compose:
      file: code/boot/src/test/resources/compose/docker-compose.yml
      enabled: false

server:
  servlet:
    context-path: /flowrapp
  port: 8080
