

spring:
  docker:
    compose:
      enabled: false
  datasource:
      main-postgres:
        jdbcUrl: jdbc:postgresql://ep-summer-heart-a9c3ig3a-pooler.gwc.azure.neon.tech/flowrapp
        username: ${MAIN_POSTGRES_USERNAME}
        password: ${MAIN_POSTGRES_PASSWORD}

