logging:
  level:
    io.github.flowrapp: DEBUG

spring:
  datasource:
    neon-azure:
      jdbcUrl: jdbc:postgresql://ep-summer-heart-a9c3ig3a-pooler.gwc.azure.neon.tech/flowrapp
      username: ${NEON_AZURE_USERNAME}
      password: ${NEON_AZURE_PASSWORD}
