spring:
  application:
    name: flowrapp

  mvc:
    problemdetails:
      enabled: true

  threads:
    virtual:
      enabled: false # Enable for virtual threads

  thymeleaf:
    cache: false

  # Datasource Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SCHEMA:flowrapp_management}
  datasource:
    neon-azure:
      driverClassName: org.postgresql.Driver
  docker:
    compose:
      file: code/boot/src/test/resources/compose/docker-compose.yml
      enabled: false

app:
  # OAuth2 Client Configuration
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}

  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
    paths:
      invitation: ${FRONTEND_INVITATION_PATH:/invitation}
      invitation-register: ${FRONTEND_INVITATION_REGISTER_PATH:/invitation-register}

  # Mail Configuration
simplejavamail:
  smtp:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
  defaults:
    fromname: ${MAIL_FROM_NAME:Flowr}
    fromaddress: ${MAIL_FROM_ADDRESS:no-reply@flowr.app}
  transportstrategy: SMTP_TLS

# Swagger OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  packages-to-scan: io.github.flowrapp.infrastructure.input.rest

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]

server:
  servlet:
    context-path: /flowrapp
  port: 8080
