spring:
  mvc:
    problemdetails:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    main-postgres:
      driverClassName: org.postgresql.Driver
  docker:
    compose:
      file: code/boot/src/test/resources/compose/docker-compose.yml

server:
  servlet:
    context-path: /flowrapp
  port: 8080
