logging:
  level:
    io.github.flowrapp: WARN

spring:
  datasource:
    main-postgres:
      jdbcUrl: jdbc:postgresql://${MAIN_POSTGRES_URL}/${MAIN_POSTGRES_DB_NAME}
      username: ${MAIN_POSTGRES_USERNAME}
      password: ${MAIN_POSTGRES_PASSWORD}